platform :osx, '10.9'
workspace '../NSAttributedString+CCLFormat'

pod 'NSAttributedString+CCLFormat', :path => '../'

begin
  require 'slather'
  Slather.prepare_pods(self)
rescue LoadError
  puts 'Slather has been disabled (not installed).'
end

